name: "[Demo] Run Scan Action"

on: [push]

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Always testing the main branch
    - uses: anchore/scan-action@main
      with:
        image: "python:3.8"
        debug: true

  image-fail-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Always testing the main branch
    - uses: anchore/scan-action@main
      with:
        image: "python:3.8"
        debug: true

  image-severity:
    runsv-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Always testing the main branch
    - uses: anchore/scan-action@main
      with:
        image: "python:3.8"
        debug: true

  image-severity-fail-build:
    runsv-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Always testing the main branch
    - uses: anchore/scan-action@main
      with:
        image: "python:3.8"
        debug: true
        fail-build: true
        severity-cutoff: Medium

  test-directory:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        path: "tests/python"
        debug: true
        severity-cutoff: "Negligible"
