name: "[SARIF] Run Scan Action"

on:
  # allow running on-demand
  workflow_dispatch:
  schedule:
    # Nightly
    - cron: "0 0 * * *"

jobs:
  sarif-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Run the local Scan Action with SARIF generation enabled
      uses: anchore/scan-action@next
      with:
        image: "ubuntu:latest"
        debug: true
        fail-build: false
        acs-report-enable: true

    - name: Inspect Generated SARIF
      run: cat results.sarif

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif

  sarif-directory:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Run the local Scan Action with SARIF generation enabled
      uses: anchore/scan-action@main
      with:
        path: "tests/python"
        debug: true
        acs-report-enable: true

    - name: Inspect Generated SARIF
      run: cat results.sarif

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
